name: Churn CI

# Events 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Actions or Jobs
jobs: 

  test: # Job to run testing
    runs-on: ubuntu-latest
  
    steps:
      # Step 1: Check out the code from the repository 
      - name: Check out code 
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: "3.12"
      
      # Adding caching to save pip installs so it dosen't install on every commit
       - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests 
      - name: Test with pytest
        run: pytest

  build-and-publish:
    needs: test # Wait for test job to complete successfully
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/prediction-churn-app:latest